model:
  target: semanticodec.modules.decoder.latent_diffusion.models.ddpm.LatentDiffusion
  params:
    # Autoencoder
    first_stage_config:
      base_learning_rate: 8.0e-06
      target: latent_encoder.autoencoder.AutoencoderKL
      params: 
        reload_from_ckpt: "/mnt/bn/lqhaoheliu/exps/checkpoints/audioldm/vae_32k/2023_06_22_vae_16k_64_4/last.ckpt"
        sampling_rate: 16000
        batchsize: 16
        monitor: val/rec_loss
        image_key: fbank
        subband: 1
        embed_dim: 8
        time_shuffle: 1
        lossconfig:
          target: semanticodec.modules.decoder.latent_diffusion.modules.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 1000.0
            disc_weight: 0.5
            disc_in_channels: 1
        ddconfig:
          double_z: true
          mel_bins: 64 # The frequency bins of mel spectrogram
          z_channels: 8
          resolution: 256
          downsample_time: false
          in_channels: 1
          out_ch: 1
          ch: 128 
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
    
    # Other parameters
    base_learning_rate: 1.0e-4
    sampling_rate: 16000
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    timesteps: 1000
    parameterization: v # [eps, x0, v]
    first_stage_key: fbank
    latent_t_size: 256 # TODO might need to change
    latent_f_size: 16
    channels: 8 # TODO might need to change
    scale_by_std: true
    unet_config:
      target: semanticodec.modules.decoder.latent_diffusion.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64 # Ignore this parameter
        # Conditioning
        # extra_film_condition_dim: 512 # If you use film as extra condition, set this parameter. For example if you have two conditioning vectors each have dimension 512, then this number would be 1024
        context_dim: 
        - 3264
        in_channels: 8 # The input channel of the UNet model
        out_channels: 8 # TODO might need to change
        model_channels: 64
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult: 
        - 1
        - 2
        - 3
        - 5
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
    
    cond_stage_config:
      crossattn_audiomae_pooled:
        cond_stage_key: ta_kaldi_fbank
        conditioning_key: crossattn
        target: semanticodec.modules.encoder.encoder.AudioMAEConditionQuantResEncoder
        params: 
          # Use normal AudioMAE centroid
          codebook_size: 8192
          feature_dimension: 1536 # 768 means 1.33 kbps, 768*2 means 0.66 kbps, 768*4 means 0.33 kbps
          residual_encoder: lstm # ResidualLSTM
          lstm_layer: 3
          rvq_layers: 0
          use_oracle: false
          lstm_bidirectional: true